// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroVibe.Infrastructure.Persistence;

#nullable disable

namespace RetroVibe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RetroVibeDbContext))]
    [Migration("20260825212749_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RetroVibe.Domain.Entities.ActionItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AssigneeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assignee_id");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("comments_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("action_items", (string)null);
                });

            modelBuilder.Entity("RetroVibe.Domain.Entities.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_kind");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentKind", "ParentId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("RetroVibe.Domain.Entities.RetroSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double?>("FeedbackScore")
                        .HasColumnType("REAL")
                        .HasColumnName("feedback_score");

                    b.Property<int>("ParticipantsCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("participants_count");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phase");

                    b.Property<string>("PrivacyMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("privacy_mode");

                    b.Property<string>("SquadId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("squad_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_id");

                    b.Property<string>("ThemeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("theme_id");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("SquadId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("RetroVibe.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("access_level");

                    b.Property<string>("AllowedSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_session_id");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("SquadId")
                        .HasColumnType("TEXT")
                        .HasColumnName("squad_id");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RetroVibe.Infrastructure.Persistence.Rows.SquadRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("squads", (string)null);
                });

            modelBuilder.Entity("RetroVibe.Infrastructure.Persistence.Rows.TemplateColumnRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_index");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("template_columns", (string)null);
                });

            modelBuilder.Entity("RetroVibe.Infrastructure.Persistence.Rows.TemplateRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_custom");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("RetroVibe.Infrastructure.Persistence.Rows.ThemeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("emoji");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("themes", (string)null);
                });

            modelBuilder.Entity("RetroVibe.Domain.Entities.RetroSession", b =>
                {
                    b.OwnsOne("RetroVibe.Domain.Entities.PhaseDurations", "PhaseDurations", b1 =>
                        {
                            b1.Property<string>("RetroSessionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CollectMinutes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("collect_minutes");

                            b1.Property<int>("DiscussMinutes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("discuss_minutes");

                            b1.Property<int>("VoteMinutes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("vote_minutes");

                            b1.HasKey("RetroSessionId");

                            b1.ToTable("sessions");

                            b1.WithOwner()
                                .HasForeignKey("RetroSessionId");
                        });

                    b.OwnsMany("RetroVibe.Domain.Entities.RetroColumn", "Columns", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<string>("Icon")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("icon");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("key");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("label");

                            b1.Property<int>("Order")
                                .HasColumnType("INTEGER")
                                .HasColumnName("order_index");

                            b1.Property<string>("SessionId")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("session_id");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.ToTable("columns", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionId");

                            b1.OwnsMany("RetroVibe.Domain.Entities.RetroCard", "Cards", b2 =>
                                {
                                    b2.Property<string>("Id")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("id");

                                    b2.Property<string>("AuthorId")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("author_id");

                                    b2.Property<string>("ColumnId")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("column_id");

                                    b2.Property<int>("CommentsCount")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("comments_count");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("created_at");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("text");

                                    b2.PrimitiveCollection<string>("_voterIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("voter_ids");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ColumnId");

                                    b2.ToTable("cards", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ColumnId");
                                });

                            b1.Navigation("Cards");
                        });

                    b.Navigation("Columns");

                    b.Navigation("PhaseDurations");
                });

            modelBuilder.Entity("RetroVibe.Infrastructure.Persistence.Rows.TemplateColumnRow", b =>
                {
                    b.HasOne("RetroVibe.Infrastructure.Persistence.Rows.TemplateRow", null)
                        .WithMany("Columns")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RetroVibe.Infrastructure.Persistence.Rows.TemplateRow", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
